//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zs.Web.Tbl_Xueyuan {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtnameen;
		protected global::System.Web.UI.WebControls.TextBox txtlogo;
		protected global::System.Web.UI.WebControls.TextBox txtimage1;
		protected global::System.Web.UI.WebControls.TextBox txtimage2;
		protected global::System.Web.UI.WebControls.TextBox txtimage3;
		protected global::System.Web.UI.WebControls.TextBox txtyuanzhang;
		protected global::System.Web.UI.WebControls.TextBox txtconts;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
