//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zs.Web.Tbl_Message {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtmail;
		protected global::System.Web.UI.WebControls.TextBox txttel;
		protected global::System.Web.UI.WebControls.TextBox txtconts;
		protected global::System.Web.UI.WebControls.TextBox txtaskTime;
		protected global::System.Web.UI.WebControls.TextBox txtreply;
		protected global::System.Web.UI.WebControls.TextBox txtreplyTime;
		protected global::System.Web.UI.WebControls.TextBox txtisShow;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
